# phpバージョン指定
FROM php:7.4-apache

ENV LANG C.UTF-8

COPY ./php.ini /usr/local/etc/php/

# RUN cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer
COPY --from=composer:1.10.15 /usr/bin/composer /usr/bin/composer

# Required
RUN apt-get update
RUN apt-get install mcrypt libmcrypt-dev zlib1g-dev libpq-dev unzip libzip-dev libonig-dev -y
RUN docker-php-ext-install mysqli pdo_mysql zip
RUN curl -sSL https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 -o mhsendmail \
    && chmod +x mhsendmail \
    && mv mhsendmail /usr/local/bin/mhsendmail


# Enable RewriteEngine
RUN a2enmod rewrite


